import { useEffect,useMemo,useState } from 'react';
import RepresentativeLayout from '../components/RepresentativeLayout';
import { supabase } from '../lib/supabase';
const money=n=>Number(n||0).toFixed(2)+' JOD';
const RepresentativeWithdrawals=()=>{const[rep,setRep]=useState(null),[sales,setSales]=useState([]),[rows,setRows]=useState([]),[amount,setAmount]=useState(''),[wallet,setWallet]=useState(''),[number,setNumber]=useState(''),[confirm,setConfirm]=useState(''),[loading,setLoading]=useState(false),[msg,setMsg]=useState(''),[error,setError]=useState('');
 const load=async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user)return;const[r,s,w]=await Promise.all([supabase.from('representatives').select('*').eq('user_id',user.id).single(),supabase.from('commission_sales').select('commission_amount').eq('representative_id',user.id),supabase.from('commission_withdrawals').select('*').eq('representative_id',user.id).order('requested_at',{ascending:false})]);setRep(r.data);setSales(s.data||[]);setRows(w.data||[])};useEffect(()=>{load()},[]);
 const available=useMemo(()=>{const earned=sales.reduce((a,x)=>a+Number(x.commission_amount),0);const reserved=rows.filter(x=>['pending','approved','paid'].includes(x.status)).reduce((a,x)=>a+Number(x.amount),0);return Math.max(0,earned-reserved)},[sales,rows]);
 const submit=async e=>{e.preventDefault();setLoading(true);setError('');setMsg('');if(!wallet||!number||number!==confirm){setError('تأكد من المحفظة وأن رقمي المحفظة متطابقان.');setLoading(false);return}if(Number(amount)<=0||Number(amount)>available){setError('مبلغ السحب أكبر من الرصيد المتاح.');setLoading(false);return}const{error:e1}=await supabase.rpc('request_commission_withdrawal',{p_amount:Number(amount),p_wallet_type:wallet,p_wallet_number:number});if(e1)setError(e1.message);else{setMsg('تم إرسال طلب السحب بنجاح.');setAmount('');await load()}setLoading(false)};
 return <RepresentativeLayout><section className="rep-page"><div className="rep-page-title"><span className="rep-eyebrow">WITHDRAWALS</span><h1>سحب العمولة</h1><p>اطلب تحويل رصيدك المتاح إلى محفظتك الإلكترونية.</p></div><div className="rep-withdraw-grid"><div className="rep-withdraw-card"><div className="rep-balance-big"><small>الرصيد المتاح</small><strong>{money(available)}</strong></div><form onSubmit={submit}><label>المبلغ المطلوب<input type="number" min="1" step="0.01" max={available} value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label>نوع المحفظة<select value={wallet} onChange={e=>setWallet(e.target.value)} required><option value="">اختر المحفظة</option><option>Zain Cash</option><option>Orange Money</option><option>UWallet</option><option>Dinarak</option></select></label><label>رقم المحفظة<input inputMode="text" autoCapitalize="none" value={number} onChange={e=>setNumber(e.target.value)} required/></label><label>تأكيد رقم المحفظة<input inputMode="text" autoCapitalize="none" value={confirm} onChange={e=>setConfirm(e.target.value)} required/></label>{error&&<div className="rep-error">{error}</div>}{msg&&<div className="rep-success">{msg}</div>}<button className="rep-primary-btn" disabled={loading||available<=0}>{loading?'جاري إرسال الطلب...':'إرسال طلب السحب'}</button></form></div><div className="rep-panel"><div className="rep-panel-head"><h2>سجل السحوبات</h2></div>{rows.map(w=><div className="rep-row" key={w.id}><div><strong>{money(w.amount)}</strong><small>{w.wallet_type} · {w.wallet_number}</small></div><span className={'rep-status '+w.status}>{w.status==='paid'?'تم الدفع':w.status==='approved'?'موافق':w.status==='rejected'?'مرفوض':'قيد المراجعة'}</span></div>)}{!rows.length&&<div className="rep-empty">لا توجد طلبات سحب.</div>}</div></div></section></RepresentativeLayout>};export default RepresentativeWithdrawals;
