import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Wallet, TrendingUp, CircleDollarSign, ArrowDownToLine, Plus, Clock3 } from 'lucide-react';
import { supabase } from '../lib/supabase';
import RepresentativeLayout from '../components/RepresentativeLayout';

const money=n=>Number(n||0).toFixed(2)+' JOD';
const RepresentativeDashboard=()=>{
 const [rep,setRep]=useState(null),[sales,setSales]=useState([]),[withdrawals,setWithdrawals]=useState([]),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const [r,s,w]=await Promise.all([supabase.from('representatives').select('*').eq('user_id',user.id).single(),supabase.from('commission_sales').select('*').eq('representative_id',user.id).order('sale_date',{ascending:false}),supabase.from('commission_withdrawals').select('*').eq('representative_id',user.id).order('requested_at',{ascending:false})]);setRep(r.data);setSales(s.data||[]);setWithdrawals(w.data||[]);setLoading(false)})()},[]);
 const stats=useMemo(()=>{const d=new Date(),start=new Date(d.getFullYear(),d.getMonth(),1).toISOString().slice(0,10);const month=sales.filter(x=>x.sale_date>=start);const earned=sales.reduce((a,x)=>a+Number(x.commission_amount),0);const monthCommission=month.reduce((a,x)=>a+Number(x.commission_amount),0);const monthSales=month.reduce((a,x)=>a+Number(x.amount),0);const paid=withdrawals.filter(x=>['approved','paid'].includes(x.status)).reduce((a,x)=>a+Number(x.amount),0);const reserved=withdrawals.filter(x=>x.status==='pending').reduce((a,x)=>a+Number(x.amount),0);return{earned,monthCommission,monthSales,paid,available:Math.max(0,earned-paid-reserved)}},[sales,withdrawals]);
 if(loading)return <RepresentativeLayout><div className="rep-loading">جاري تحميل لوحة المندوب...</div></RepresentativeLayout>;
 return <RepresentativeLayout><section className="rep-page"><div className="rep-hero"><div><span className="rep-eyebrow">REPRESENTATIVE DASHBOARD</span><h1>مرحباً، {rep?.full_name?.split(' ')[0]||'مندوب'} 👋</h1><p>نظرة سريعة على أدائك وعمولاتك.</p></div><Link className="rep-action" to="/representative/withdrawals"><Plus size={18}/> طلب سحب</Link></div>
 <div className="rep-stat-grid"><div className="rep-stat accent"><span><Wallet size={20}/></span><small>المتاح للسحب</small><strong>{money(stats.available)}</strong></div><div className="rep-stat"><span><TrendingUp size={20}/></span><small>مبيعات هذا الشهر</small><strong>{money(stats.monthSales)}</strong></div><div className="rep-stat"><span><CircleDollarSign size={20}/></span><small>عمولة هذا الشهر</small><strong>{money(stats.monthCommission)}</strong></div><div className="rep-stat"><span><ArrowDownToLine size={20}/></span><small>إجمالي المسحوبات</small><strong>{money(stats.paid)}</strong></div></div>
 <div className="rep-grid-2"><div className="rep-panel"><div className="rep-panel-head"><h2>آخر المبيعات</h2><Link to="/representative/sales">عرض الكل</Link></div>{sales.slice(0,5).map(s=><div className="rep-row" key={s.id}><div><strong>{s.service_name}</strong><small>{s.sale_date} · {s.division||'IRIS'}</small></div><b>{money(s.commission_amount)}</b></div>)}{!sales.length&&<div className="rep-empty">لا توجد مبيعات مسجلة بعد.</div>}</div>
 <div className="rep-panel"><div className="rep-panel-head"><h2>آخر السحوبات</h2><Link to="/representative/withdrawals">عرض الكل</Link></div>{withdrawals.slice(0,5).map(w=><div className="rep-row" key={w.id}><div><strong>{money(w.amount)}</strong><small>{new Date(w.requested_at).toLocaleDateString('ar-JO')}</small></div><span className={'rep-status '+w.status}>{w.status==='paid'?'تم الدفع':w.status==='approved'?'موافق':w.status==='rejected'?'مرفوض':'قيد المراجعة'}</span></div>)}{!withdrawals.length&&<div className="rep-empty">لم تطلب أي سحب بعد.</div>}</div></div>
 <div className="rep-info-strip"><Clock3 size={18}/> المبالغ قيد المراجعة تُحجز من رصيدك المتاح حتى يتم اعتمادها أو رفضها.</div></section></RepresentativeLayout>;
};
export default RepresentativeDashboard;
